<?php

$labels = array();
$labels['next'] = 'Próximo';
$labels['prev'] = 'Anterior';
$labels['skip'] = 'Pular';
$labels['done'] = 'Pronto';
$labels['button'] = 'Tour pelo Roundcube Webmail';
$labels['welcome'] = 'Bem-vindo!<br><br>Este é o tour de apresentação dos recursos do Roundcube Webmail.<br>Para pular, clique em "Fechar".';
$labels['taskbar'] = 'Botões para alternar entre as tarefas.';
$labels['taskbar_mail'] = 'Botão da caixa de e-mail.';
$labels['taskbar_addressbook'] = 'Botão para ir para os contatos.';
$labels['taskbar_cloud'] = 'Botão para ir para o armazenamento de arquivos. <br>Aqui você pode fazer upload de quaisquer arquivos para enviar por e-mail.';
$labels['taskbar_calendar'] = 'Botão de calendário.';
$labels['taskbar_tasklist'] = 'Botão para ir para a lista de tarefas.';
$labels['taskbar_settings'] = 'Botão para ir para as configurações. <br>Aqui você pode alterar as configurações da interface, pastas, perfis, etc.';
$labels['toolbar'] = 'As principais ferramentas de mensagens estão localizadas aqui.';
$labels['toolbar_archive'] = 'Use este botão para mover as mensagens selecionadas para uma pasta de arquivo.';
$labels['toolbar_junk'] = 'Use este botão para transferir a (s) mensagem (ns) selecionada (s) para SPAM.';
$labels['folders'] = 'Exibe uma lista hierárquica de todas as pastas em sua conta de e-mail.';
$labels['quota'] = 'O espaço disponível para seus e-mails é exibido aqui.';
$labels['messages_view'] = 'Modo de exibição de letras, colunas exibidas e método de classificação.';
$labels['messages_threads'] = 'Alternar o agrupamento de mensagens por tópico.';
$labels['settings_preferences'] = 'Aqui estão as principais configurações do Roundcube Webmail.';
$labels['settings_folders'] = 'Aqui você pode gerenciar as pastas de sua conta de e-mail.';
$labels['settings_identities'] = 'Dados de sua Identidade (nome do remetente, endereço de resposta, organização, assinatura)';
$labels['settings_responses'] = 'Criar e gerenciar modelos de reposta automatizadas.';
$labels['settings_pluginmanagesieve'] = 'Configurar um filtro para processamento automático de mensagens recebidas.';
$labels['settings_pluginmanagesievevacation'] = 'Configurar uma resposta automática para mensagens recebidas durante as férias.';
$labels['settings_pluginpassword'] = 'Alterar a senha de sua conta de e-mail.';

?>
